/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CollectionIndexImport } from './routes/collection/index'
import { Route as CIndexImport } from './routes/c/index'
import { Route as CChatIdImport } from './routes/c/$chatId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CollectionIndexRoute = CollectionIndexImport.update({
  path: '/collection/',
  getParentRoute: () => rootRoute,
} as any)

const CIndexRoute = CIndexImport.update({
  path: '/c/',
  getParentRoute: () => rootRoute,
} as any)

const CChatIdRoute = CChatIdImport.update({
  path: '/c/$chatId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdImport
      parentRoute: typeof rootRoute
    }
    '/c/': {
      id: '/c/'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CIndexImport
      parentRoute: typeof rootRoute
    }
    '/collection/': {
      id: '/collection/'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$chatId': typeof CChatIdRoute
  '/c': typeof CIndexRoute
  '/collection': typeof CollectionIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$chatId': typeof CChatIdRoute
  '/c': typeof CIndexRoute
  '/collection': typeof CollectionIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/c/$chatId': typeof CChatIdRoute
  '/c/': typeof CIndexRoute
  '/collection/': typeof CollectionIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$chatId' | '/c' | '/collection'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$chatId' | '/c' | '/collection'
  id: '__root__' | '/' | '/c/$chatId' | '/c/' | '/collection/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CChatIdRoute: typeof CChatIdRoute
  CIndexRoute: typeof CIndexRoute
  CollectionIndexRoute: typeof CollectionIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CChatIdRoute: CChatIdRoute,
  CIndexRoute: CIndexRoute,
  CollectionIndexRoute: CollectionIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/c/$chatId",
        "/c/",
        "/collection/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/c/$chatId": {
      "filePath": "c/$chatId.tsx"
    },
    "/c/": {
      "filePath": "c/index.tsx"
    },
    "/collection/": {
      "filePath": "collection/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
